export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAIL = "ARTICLE_LIST_FAIL";

export const ARTICLE_DETAILS_REQUEST = "ARTICLE_DETAILS_REQUEST";
export const ARTICLE_DETAILS_SUCCESS = "ARTICLE_DETAILS_SUCCESS";
export const ARTICLE_DETAILS_FAIL = "ARTICLE_DETAILS_FAIL";

export const ARTICLE_CLAP_REQUEST = "ARTICLE_CLAP_REQUEST";
export const ARTICLE_CLAP_SUCCESS = "ARTICLE_CLAP_SUCCESS";
export const ARTICLE_CLAP_FAIL = "ARTICLE_CLAP_FAIL";

export const ARTICLE_CREATE_REQUEST = "ARTICLE_CREATE_REQUEST";
export const ARTICLE_CREATE_SUCCESS = "ARTICLE_CREATE_SUCCESS";
export const ARTICLE_CREATE_FAIL = "ARTICLE_CREATE_FAIL";
