export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL";

export const USER_LIST_FOLLOW_REQUEST = "USER_LIST_FOLLOW_REQUEST";
export const USER_LIST_FOLLOW_SUCCESS = "USER_LIST_FOLLOW_SUCCESS";
export const USER_LIST_FOLLOW_FAIL = "USER_LIST_FOLLOW_FAIL";
